name: Deploy buy runner

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: run tests
        run: mvn test
  get-artifact:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: get jar file
        run: mvn clean package -DskipTests
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_init-0.0.1-SNAPSHOT.jar
          path: ./target/test_init-0.0.1-SNAPSHOT.jar
  prepare-environment:
    runs-on: self-hosted
    needs: get-artifact
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: test_init-0.0.1-SNAPSHOT.jar
          path: ./
      - name: docker-compose
        run: docker-compose up -d